version: 0.2
 
phases:
  install:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  pre_build:
    commands:
      - echo Pre-build started
      - npm audit fix || true
  build:
    commands:
      - echo Build started
  post_build:
    commands:
      - echo Post-build started
artifacts:
  files:
    - '**/*'
cache:
  paths:
    - 'node_modules/**/*'