version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -g serverless
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npx serverless deploy

artifacts:
  base-directory: ./src
  files:
    - '**/*'
