version: 0.2
 
phases:
  install:
    commands:
      - echo Installing NPM dependencies...
      - npm install -g serverless
      - npm install
  pre_build:
    commands:
      - echo Pre-build phase...
      - npm audit fix || true
  build:
    commands:
      - echo Build phase...
      - serverless deploy --stage dev
artifacts:
  files:
    - '**/*'
cache:
  paths:
    - 'node_modules/**/*'