service: express-app

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1

functions:
  app:
    handler: src/lambda.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}

package:
  exclude:
    - node_modules/**
    - build/**
    - coverage/**
    - .git/**
    - .vscode/**
    - README.md
    - serverless.yml
    - buildspec.yml
